"""worker_final.py -- one GPU-pinned training worker for the Kaggle final+LOSO notebook.
Auto-generated by phase4_kaggle_final/04_final_loso_kaggle.ipynb -- edit the notebook cell,
not this file.
CUDA_VISIBLE_DEVICES is set by the parent process before this script starts, so
torch.device("cuda") always refers to this worker's assigned physical GPU.

Two job kinds:
  "final" -- the fixed train/{set05,set06}-val/set03-test split (engine.split_data),
             full run dir written by train_run(out_dir=...). Used for Stage D and the
             determinism-of-record rerun. eval_test=True -- THIS is where test set03
             gets touched.
  "loso"  -- one leave-one-set-out fold: test = the named set, train+val = the other
             5 sets split 85/15 by pedestrian (grouped, Issue-5 protocol), per-fold
             pos_weight. No checkpoint dir -- the augmented result dict is written
             straight to out_path.
"""
import argparse
import importlib.util
import json
import pickle
from pathlib import Path

import numpy as np


def loso_fold_data(X, y, set_ids, ped_ids, fold_set, seed, val_frac=0.15):
    te = set_ids == fold_set
    pool = ~te
    pool_peds = np.unique(ped_ids[pool])
    rng = np.random.default_rng(seed)
    rng.shuffle(pool_peds)
    n_val = max(1, int(round(len(pool_peds) * val_frac)))
    val_peds = set(pool_peds[:n_val].tolist())
    is_val = np.array([p in val_peds for p in ped_ids])
    va = pool & is_val
    tr = pool & ~is_val
    data = (X[tr], y[tr], X[va], y[va], X[te], y[te])
    pw = float((y[tr] == 0).sum() / max(1, (y[tr] == 1).sum()))
    counts = dict(train_n=int(tr.sum()), val_n=int(va.sum()), test_n=int(te.sum()),
                 test_pos=float(y[te].mean()))
    return data, pw, counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jobs", required=True)
    ap.add_argument("--seq_dir", required=True)
    ap.add_argument("--here", required=True)
    args = ap.parse_args()

    here = Path(args.here)
    spec = importlib.util.spec_from_file_location("train_engine", here / "02_train_transformer.py")
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)

    import torch
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    seq_dir = Path(args.seq_dir)
    X, y, set_ids = engine.load_raw(seq_dir)
    fixed_data = engine.split_data(X, y, set_ids)
    with open(seq_dir / "meta.pkl", "rb") as f:
        meta = pickle.load(f)
    ped_ids = np.array([f"{m['set_id']}/{m['ped_id']}" for m in meta])

    jobs = json.loads(Path(args.jobs).read_text())

    for job in jobs:
        if job["kind"] == "final":
            out_dir = Path(job["out_dir"])
            if (out_dir / "final.json").exists():
                print(f"[worker] cached final {job.get('tag', '?')} seed{job['seed']} "
                      f"-> {out_dir}", flush=True)
                continue
            result = engine.train_run(job["cfg"], job["seed"], device, fixed_data,
                                      eval_test=True, out_dir=out_dir)
            print(f"[worker] done final {job.get('tag', '?')} seed{job['seed']} "
                  f"valAUC={result['val']['auc']:.4f} testAUC={result['test']['auc']:.4f} "
                  f"({result['seconds']}s)", flush=True)

        elif job["kind"] == "loso":
            out_path = Path(job["out_path"])
            if out_path.exists():
                print(f"[worker] cached loso {job['fold_set']}", flush=True)
                continue
            data, pw, counts = loso_fold_data(X, y, set_ids, ped_ids, job["fold_set"],
                                              job["seed"])
            result = engine.train_run(job["cfg"], job["seed"], device, data,
                                      eval_test=True, out_dir=None, pos_weight=pw)
            result.update(test_set=job["fold_set"], **counts)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(result, indent=2, default=str))
            print(f"[worker] done loso {job['fold_set']} valAUC={result['val']['auc']:.4f} "
                  f"testAUC={result['test']['auc']:.4f} pw={pw:.3f} "
                  f"({result['seconds']}s)", flush=True)

        else:
            raise ValueError(f"unknown job kind: {job['kind']!r}")


if __name__ == "__main__":
    main()
