"""gen_search_nb.py -- regenerates 03_search_kaggle.ipynb.

Run this whenever phase1_setup/00_transformer_model.py or
phase1_setup/02_train_transformer.py change, so the notebook's embedded copies stay in
sync (the "KEEP IN SYNC" banners in the notebook point back here). Builds the notebook
as a plain dict (nbformat v4 schema) so all string escaping is handled by
json.dump / repr(), not by hand.

    python transformer/phase2_kaggle_search/gen_search_nb.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
PHASE1 = REPO / "transformer" / "phase1_setup"
MODEL_CODE = (PHASE1 / "00_transformer_model.py").read_text()
ENGINE_CODE = (PHASE1 / "02_train_transformer.py").read_text()

WORKER_CODE = '''"""worker.py -- one GPU-pinned training worker for the Kaggle search notebook.
Auto-generated by phase2_kaggle_search/03_search_kaggle.ipynb -- edit the notebook cell,
not this file.
CUDA_VISIBLE_DEVICES is set by the parent process before this script starts, so
torch.device("cuda") always refers to this worker's assigned physical GPU.
"""
import argparse
import importlib.util
import json
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jobs", required=True)
    ap.add_argument("--seq_dir", required=True)
    ap.add_argument("--out_root", required=True)
    ap.add_argument("--here", required=True)
    args = ap.parse_args()

    here = Path(args.here)
    spec = importlib.util.spec_from_file_location("train_engine", here / "02_train_transformer.py")
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)

    import torch
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    X, y, set_ids = engine.load_raw(Path(args.seq_dir))
    data = engine.split_data(X, y, set_ids)

    jobs = json.loads(Path(args.jobs).read_text())
    out_root = Path(args.out_root)

    for job in jobs:
        assert not job["eval_test"], (
            "search notebook must never evaluate the test set -- "
            f"got eval_test=True for {job['cfg_id']} seed{job['seed']}"
        )
        out_path = out_root / job["cfg_id"] / f"seed{job['seed']}.json"
        if out_path.exists():
            print(f"[worker] cached {job['cfg_id']} seed{job['seed']}", flush=True)
            continue
        out_path.parent.mkdir(parents=True, exist_ok=True)
        result = engine.train_run(job["cfg"], job["seed"], device, data,
                                  eval_test=False, out_dir=None)
        out_path.write_text(json.dumps(result, indent=2, default=str))
        print(f"[worker] done {job['cfg_id']} seed{job['seed']} "
              f"valAUC={result['val']['auc']:.4f} ({result['seconds']}s)", flush=True)


if __name__ == "__main__":
    main()
'''

# --- notebook cell sources (as plain python source strings) ---

CELL_MD_TITLE = """# Transformer staged search -- Stage A (architecture) + Stage B (recipe) + transfer check + Stage C (candidate multiseed)

Runs the `transformer/PLAN.md` #4 staged search, **val-only** -- no test-evaluation code
path exists anywhere in this notebook. Test set03 is touched only in
`phase4_kaggle_final/04_final_loso_kaggle.ipynb`, exactly once, after the winner is
reviewed locally.

**Setup before Run All:**
1. Upload `sequences_clean/{X.npy,y.npy,meta.pkl}` (`transformer/sequences_clean/` in the
   repo) as a private Kaggle dataset named `pie-sequences-clean`, and attach it to this
   notebook.
2. Settings -> Accelerator -> **GPU T4 x2**.
3. Run All.

**Output:** `runs_search/<cfg_id>/seed<k>.json` per config (val-only schema -- no `test`
key, ever) + `runs_search/_stage_summary.json`, zipped to
`/kaggle/working/transformer_search_output.zip`. Download it, unzip into
`transformer/phase2_kaggle_search/` so `runs_search/` sits there, then run
`transformer/phase3_search_review/03_search_report.py` locally -- that is the Phase-T3
human checkpoint, before the winner config is pasted into
`phase4_kaggle_final/04_final_loso_kaggle.ipynb`.

Nothing here should diverge from `transformer/PLAN.md` sections 3-4 (the grids, the
`transformer_default` config, the selection rules) -- if it does, PLAN.md is stale and
should be corrected, not this notebook."""

CELL_ENV_CHECK = """import json, os, subprocess, sys, tempfile, time
from pathlib import Path

import numpy as np
import pandas as pd
import torch

print("python:", sys.version)
print("torch:", torch.__version__)
n_gpu = torch.cuda.device_count()
print("CUDA available:", torch.cuda.is_available(), "| device count:", n_gpu)
for i in range(n_gpu):
    print(f"  cuda:{i} = {torch.cuda.get_device_name(i)}")
if n_gpu != 2:
    print(f"WARNING: expected 2x T4 (transformer/PLAN.md #5), found {n_gpu} GPU(s). "
          f"Continuing with {max(n_gpu, 1)} worker(s) -- this only affects wall-clock, "
          f"not correctness.")

GPU_IDS = list(range(n_gpu)) if n_gpu > 0 else [None]  # None => CPU fallback (slow, not expected)
print("worker GPU ids:", GPU_IDS)"""

CELL_LOCATE_DATA = """candidates = [Path("/kaggle/input/pie-sequences-clean")]
candidates += sorted(Path("/kaggle/input").glob("*"))
SEQ_DIR = None
for c in candidates:
    if (c / "X.npy").exists() and (c / "y.npy").exists() and (c / "meta.pkl").exists():
        SEQ_DIR = c
        break
assert SEQ_DIR is not None, (
    "Could not find sequences_clean/{X.npy,y.npy,meta.pkl} under /kaggle/input/. "
    "Attach the 'pie-sequences-clean' dataset (see the markdown cell above)."
)
print("using sequences from:", SEQ_DIR)

X_check = np.load(SEQ_DIR / "X.npy", mmap_mode="r")
assert X_check.shape == (4906, 16, 5), (
    f"unexpected X shape {X_check.shape} -- this must be the CLEAN sequences_clean/ "
    f"(N=4906), not the old leaky sequences/ (N=1389). Re-upload the correct dataset."
)
print(f"asserted clean data: X.shape == {X_check.shape}")

HERE_DIR = Path("/kaggle/working")
OUT_ROOT = HERE_DIR / "runs_search"
OUT_ROOT.mkdir(parents=True, exist_ok=True)
SEEDS = [42, 0, 1, 2, 3]
print("out_root:", OUT_ROOT)"""

CELL_WRITE_MODEL = f"""# KEEP IN SYNC WITH transformer/00_transformer_model.py -- edit there first, then
# regenerate this notebook (see gen_search_nb.py). Do not hand-edit this cell.
model_code = {MODEL_CODE!r}
(HERE_DIR / "00_transformer_model.py").write_text(model_code)
print("wrote", HERE_DIR / "00_transformer_model.py", f"({{len(model_code)}} bytes)")"""

CELL_WRITE_ENGINE = """# KEEP IN SYNC WITH transformer/02_train_transformer.py -- edit there first, then
# regenerate this notebook (see gen_search_nb.py). Do not hand-edit this cell.
engine_code = %r
(HERE_DIR / "02_train_transformer.py").write_text(engine_code)
print("wrote", HERE_DIR / "02_train_transformer.py", f"({len(engine_code)} bytes)")

import importlib.util
_spec_engine = importlib.util.spec_from_file_location(
    "train_engine", HERE_DIR / "02_train_transformer.py")
engine = importlib.util.module_from_spec(_spec_engine)
_spec_engine.loader.exec_module(engine)
print("loaded engine module; DEFAULT_CFG =", engine.DEFAULT_CFG)""" % ENGINE_CODE

CELL_WRITE_WORKER = f"""# Auto-generated worker script -- see gen_search_nb.py's WORKER_CODE.
worker_code = {WORKER_CODE!r}
(HERE_DIR / "worker.py").write_text(worker_code)
print("wrote", HERE_DIR / "worker.py", f"({{len(worker_code)}} bytes)")"""

CELL_HELPERS = """# --- config identity, grids, and the 2-GPU subprocess runner ---
#
# cfg_id() MUST encode every field that changes training behaviour, including
# `optimizer` -- Stage A trains with Adam (the frozen default recipe) and Stage B
# always uses AdamW, so a Stage-B cell can numerically match Stage A's default recipe
# on every OTHER field (lr=1e-3, schedule=plateau, dropout=0.1, wd=1e-5) while differing
# only in optimizer. Omitting `optimizer` from the id would collide the two into the
# same cache path and silently discard one run's result.

ARCH_KEYS = ["d_model", "nhead", "num_layers", "dim_ff", "pool", "pos"]
RECIPE_KEYS = ["lr", "schedule", "dropout", "weight_decay", "optimizer"]

ARCH_D_FF = [(64, 128), (128, 256), (128, 512)]
ARCH_LAYERS = [2, 4]
ARCH_POOL = ["cls", "mean", "last"]
ARCH_POS = ["learned", "sin"]

RECIPE_LR = [1e-4, 3e-4, 1e-3]
RECIPE_SCHEDULE = ["plateau", "warmup_cosine"]
RECIPE_DROPOUT = [0.1, 0.3, 0.5]
RECIPE_WD = [1e-5, 1e-2]


def pos_abbrev(pos):
    return "lpe" if pos == "learned" else "spe"


def cfg_id(cfg):
    arch = f"d{cfg['d_model']}_ff{cfg['dim_ff']}_L{cfg['num_layers']}_{cfg['pool']}_{pos_abbrev(cfg['pos'])}"
    recipe = (f"{cfg['optimizer']}_lr{cfg['lr']:.0e}_{cfg['schedule']}_"
             f"do{cfg['dropout']}_wd{cfg['weight_decay']:.0e}")
    return f"{arch}__{recipe}"


def arch_only(cfg):
    return {k: cfg[k] for k in ARCH_KEYS}


def recipe_only(cfg):
    return {k: cfg[k] for k in RECIPE_KEYS}


DEFAULT_CFG = engine.DEFAULT_CFG
DEFAULT_RECIPE = recipe_only(DEFAULT_CFG)
print("DEFAULT_RECIPE:", DEFAULT_RECIPE, "\\ndefault cfg_id:", cfg_id(DEFAULT_CFG))


def build_stage_a_grid(recipe=None):
    recipe = recipe or DEFAULT_RECIPE
    grid = []
    for d_model, ff in ARCH_D_FF:
        for L in ARCH_LAYERS:
            for pool in ARCH_POOL:
                for pos in ARCH_POS:
                    grid.append(dict(d_model=d_model, nhead=4, num_layers=L, dim_ff=ff,
                                     pool=pool, pos=pos, **recipe))
    return grid  # 3*2*3*2 = 36


def build_stage_b_grid(arch_cfg):
    base_arch = arch_only(arch_cfg)
    grid = []
    for lr in RECIPE_LR:
        for schedule in RECIPE_SCHEDULE:
            for dropout in RECIPE_DROPOUT:
                for wd in RECIPE_WD:
                    grid.append(dict(**base_arch, lr=lr, schedule=schedule, dropout=dropout,
                                     weight_decay=wd, optimizer="adamw"))
    return grid  # 3*2*3*2 = 36


def build_transfer_grid(recipe_cfgs, arch_cfgs):
    grid = []
    for r in recipe_cfgs:
        for a in arch_cfgs:
            grid.append(dict(**arch_only(a), **recipe_only(r)))
    return grid  # len(recipe_cfgs) * len(arch_cfgs)


def make_jobs(cfgs, seed):
    return [dict(cfg=c, seed=seed, eval_test=False, cfg_id=cfg_id(c)) for c in cfgs]


def make_jobs_multiseed(cfgs, seeds):
    return [dict(cfg=c, seed=s, eval_test=False, cfg_id=cfg_id(c)) for c in cfgs for s in seeds]


def run_stage_parallel(jobs, gpu_ids, label=""):
    shards = [[] for _ in gpu_ids]
    for i, job in enumerate(jobs):
        shards[i % len(gpu_ids)].append(job)

    procs, shard_files = [], []
    t0 = time.time()
    for gpu, shard in zip(gpu_ids, shards):
        if not shard:
            continue
        f = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, dir=str(HERE_DIR))
        json.dump(shard, f)
        f.close()
        shard_files.append(f.name)
        env = dict(os.environ)
        if gpu is not None:
            env["CUDA_VISIBLE_DEVICES"] = str(gpu)
        proc = subprocess.Popen(
            [sys.executable, str(HERE_DIR / "worker.py"),
             "--jobs", f.name, "--seq_dir", str(SEQ_DIR),
             "--out_root", str(OUT_ROOT), "--here", str(HERE_DIR)],
            env=env,
        )
        procs.append(proc)
        print(f"[{label}] launched worker on gpu={gpu} with {len(shard)} job(s)")

    for p in procs:
        ret = p.wait()
        if ret != 0:
            raise RuntimeError(f"[{label}] worker exited with code {ret}")
    for fn in shard_files:
        os.unlink(fn)
    print(f"[{label}] all workers done in {time.time() - t0:.0f}s")


def load_stage_results(jobs):
    results = []
    for job in jobs:
        p = OUT_ROOT / job["cfg_id"] / f"seed{job['seed']}.json"
        if not p.exists():
            raise FileNotFoundError(f"missing result: {p}")
        results.append(json.loads(p.read_text()))
    return results


def rank_by_val_auc(results):
    return sorted(results, key=lambda r: r["val"]["auc"], reverse=True)"""

CELL_STAGE_A = """print("=== Stage A: architecture grid (36 configs, seed 42, val-only) ===")
stage_a_grid = build_stage_a_grid()
stage_a_jobs = make_jobs(stage_a_grid, seed=42)
assert len(stage_a_jobs) == 36, len(stage_a_jobs)
run_stage_parallel(stage_a_jobs, GPU_IDS, label="Stage A")
stage_a_results = load_stage_results(stage_a_jobs)

n_diverged = sum(1 for r in stage_a_results if r["val"]["auc"] < 0.70)
if n_diverged > len(stage_a_results) // 3:
    print(f"CONTINGENCY (PLAN.md #4): {n_diverged}/{len(stage_a_results)} cells diverged "
          f"(val AUC < 0.70) at lr=1e-3 -- rerunning Stage A once at lr=3e-4.")
    recipe_lo = dict(DEFAULT_RECIPE)
    recipe_lo["lr"] = 3e-4
    stage_a_grid = build_stage_a_grid(recipe=recipe_lo)
    stage_a_jobs = make_jobs(stage_a_grid, seed=42)
    run_stage_parallel(stage_a_jobs, GPU_IDS, label="Stage A (lr=3e-4 amendment)")
    stage_a_results = load_stage_results(stage_a_jobs)

stage_a_ranked = rank_by_val_auc(stage_a_results)
df_a = pd.DataFrame([
    {**{k: r[k] for k in ["d_model", "dim_ff", "num_layers", "pool", "pos"]},
     "val_auc": r["val"]["auc"], "n_params": r["n_params"]}
    for r in stage_a_ranked
])
print(df_a.head(10).to_string(index=False))

arch_top3 = [stage_a_ranked[i] for i in range(3)]
print("\\nStage-A top-3 architectures:")
for i, r in enumerate(arch_top3, 1):
    print(f"  #{i}: {cfg_id(r)}  val_auc={r['val']['auc']:.4f}")"""

CELL_STAGE_B = """print("\\n=== Stage B: training-recipe grid on Stage-A #1 (36 configs, seed 42, val-only) ===")
stage_b_grid = build_stage_b_grid(arch_top3[0])
stage_b_jobs = make_jobs(stage_b_grid, seed=42)
assert len(stage_b_jobs) == 36, len(stage_b_jobs)
run_stage_parallel(stage_b_jobs, GPU_IDS, label="Stage B")
stage_b_results = load_stage_results(stage_b_jobs)
stage_b_ranked = rank_by_val_auc(stage_b_results)

df_b = pd.DataFrame([
    {**{k: r[k] for k in ["lr", "schedule", "dropout", "weight_decay", "optimizer"]},
     "val_auc": r["val"]["auc"]}
    for r in stage_b_ranked
])
print(df_b.head(10).to_string(index=False))

recipe_top3 = [stage_b_ranked[i] for i in range(3)]
print("\\nStage-B top-3 recipes (on architecture #1):")
for i, r in enumerate(recipe_top3, 1):
    print(f"  #{i}: {cfg_id(r)}  val_auc={r['val']['auc']:.4f}")"""

CELL_TRANSFER = """print("\\n=== Transfer check: top-3 recipes x Stage-A architectures #2, #3 (6 configs, seed 42) ===")
transfer_grid = build_transfer_grid(recipe_top3, [arch_top3[1], arch_top3[2]])
transfer_jobs = make_jobs(transfer_grid, seed=42)
assert len(transfer_jobs) == 6, len(transfer_jobs)
run_stage_parallel(transfer_jobs, GPU_IDS, label="Transfer check")
transfer_results = load_stage_results(transfer_jobs)
for r in rank_by_val_auc(transfer_results):
    print(f"  {cfg_id(r)}  val_auc={r['val']['auc']:.4f}")"""

CELL_STAGE_C = """print("\\n=== Stage C: candidate multiseed (top-5 pooled + transformer_default, 5 seeds, val-only) ===")
pool = stage_a_results + stage_b_results + transfer_results
pool_ranked = rank_by_val_auc(pool)

seen_ids, top5_cfgs = set(), []
for r in pool_ranked:
    cid = cfg_id(r)
    if cid in seen_ids:
        continue
    seen_ids.add(cid)
    top5_cfgs.append({k: r[k] for k in ARCH_KEYS + RECIPE_KEYS})
    if len(top5_cfgs) == 5:
        break

candidates = list(top5_cfgs)
if cfg_id(DEFAULT_CFG) not in {cfg_id(c) for c in candidates}:
    candidates.append(dict(DEFAULT_CFG))

print(f"Stage-C candidates ({len(candidates)}):")
for c in candidates:
    tag = "  <- transformer_default" if cfg_id(c) == cfg_id(DEFAULT_CFG) else ""
    print(f"  {cfg_id(c)}{tag}")

stage_c_jobs = make_jobs_multiseed(candidates, SEEDS)
run_stage_parallel(stage_c_jobs, GPU_IDS, label="Stage C")
stage_c_results = load_stage_results(stage_c_jobs)

rows = []
for c in candidates:
    cid = cfg_id(c)
    vals = [r["val"]["auc"] for r in stage_c_results if cfg_id(r) == cid]
    rows.append({"cfg_id": cid, "n_seeds": len(vals),
                 "val_auc_mean": float(np.mean(vals)),
                 "val_auc_std": float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0})
df_c = pd.DataFrame(rows).sort_values("val_auc_mean", ascending=False)
print(df_c.to_string(index=False))

winner_cid = df_c.iloc[0]["cfg_id"]
winner_cfg = next(c for c in candidates if cfg_id(c) == winner_cid)
is_default = winner_cid == cfg_id(DEFAULT_CFG)
print(f"\\nWINNER (highest mean val AUC): {winner_cid}"
     f"{'  (== transformer_default)' if is_default else ''}")"""

CELL_SAVE_ZIP = """summary = {
    "stage_a_top3": [{"cfg": {k: r[k] for k in ARCH_KEYS + RECIPE_KEYS}, "val_auc": r["val"]["auc"]}
                     for r in arch_top3],
    "stage_b_top3": [{"cfg": {k: r[k] for k in ARCH_KEYS + RECIPE_KEYS}, "val_auc": r["val"]["auc"]}
                     for r in recipe_top3],
    "stage_c_candidates": rows,
    "winner_cfg_id": winner_cid,
    "winner_cfg": winner_cfg,
    "winner_is_default": is_default,
    "default_cfg_id": cfg_id(DEFAULT_CFG),
    "default_cfg": DEFAULT_CFG,
    "seeds": SEEDS,
}
(OUT_ROOT / "_stage_summary.json").write_text(json.dumps(summary, indent=2, default=str))
print("wrote", OUT_ROOT / "_stage_summary.json")

import shutil
zip_path = Path("/kaggle/working/transformer_search_output.zip")
if zip_path.exists():
    zip_path.unlink()
shutil.make_archive(str(zip_path.with_suffix("")), "zip", root_dir=str(OUT_ROOT))
print(f"\\nDONE. Download {zip_path} and unzip its contents into "
     f"transformer/phase2_kaggle_search/ (so runs_search/ sits there), then run "
     f"transformer/phase3_search_review/03_search_report.py locally "
     f"(Phase T3 -- review the winner BEFORE phase4_kaggle_final/ ever touches test).")"""

CELL_MD_NEXT = """## Next steps

1. Download `/kaggle/working/transformer_search_output.zip`.
2. Unzip into `transformer/phase2_kaggle_search/` so `runs_search/` sits at
   `transformer/phase2_kaggle_search/runs_search/`.
3. Locally: `python transformer/phase3_search_review/03_search_report.py` -- re-derives
   the ranking tables/figure and prints the winner. **Review it (Phase T3) before
   proceeding** -- test set03 still does not exist anywhere yet.
4. Paste the winner config into `phase4_kaggle_final/04_final_loso_kaggle.ipynb`'s
   CONFIG cell and run it -- that notebook touches test exactly once (Stage D) and runs
   the 6-fold LOSO."""


def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


cells = [
    md_cell(CELL_MD_TITLE),
    code_cell(CELL_ENV_CHECK),
    code_cell(CELL_LOCATE_DATA),
    code_cell(CELL_WRITE_MODEL),
    code_cell(CELL_WRITE_ENGINE),
    code_cell(CELL_WRITE_WORKER),
    code_cell(CELL_HELPERS),
    code_cell(CELL_STAGE_A),
    code_cell(CELL_STAGE_B),
    code_cell(CELL_TRANSFER),
    code_cell(CELL_STAGE_C),
    code_cell(CELL_SAVE_ZIP),
    md_cell(CELL_MD_NEXT),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out_path = HERE / "03_search_kaggle.ipynb"
out_path.write_text(json.dumps(notebook, indent=1))
print("wrote", out_path)

# --- validate: JSON parses, every code cell compiles ---
loaded = json.loads(out_path.read_text())
n_code = 0
for i, cell in enumerate(loaded["cells"]):
    if cell["cell_type"] != "code":
        continue
    n_code += 1
    src = cell["source"]
    compile(src, f"<cell {i}>", "exec")
print(f"OK -- {n_code} code cells compiled without SyntaxError")
