"""gen_final_nb.py -- regenerates 04_final_loso_kaggle.ipynb.

Run this whenever phase1_setup/00_transformer_model.py or
phase1_setup/02_train_transformer.py change, so the notebook's embedded copies stay in
sync (the "KEEP IN SYNC" banners in the notebook point back here). Builds the notebook
as a plain dict (nbformat v4 schema), same technique as
phase2_kaggle_search/gen_search_nb.py.

    python transformer/phase4_kaggle_final/gen_final_nb.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
PHASE1 = REPO / "transformer" / "phase1_setup"
MODEL_CODE = (PHASE1 / "00_transformer_model.py").read_text()
ENGINE_CODE = (PHASE1 / "02_train_transformer.py").read_text()

WORKER_CODE = '''"""worker_final.py -- one GPU-pinned training worker for the Kaggle final+LOSO notebook.
Auto-generated by phase4_kaggle_final/04_final_loso_kaggle.ipynb -- edit the notebook cell,
not this file.
CUDA_VISIBLE_DEVICES is set by the parent process before this script starts, so
torch.device("cuda") always refers to this worker's assigned physical GPU.

Two job kinds:
  "final" -- the fixed train/{set05,set06}-val/set03-test split (engine.split_data),
             full run dir written by train_run(out_dir=...). Used for Stage D and the
             determinism-of-record rerun. eval_test=True -- THIS is where test set03
             gets touched.
  "loso"  -- one leave-one-set-out fold: test = the named set, train+val = the other
             5 sets split 85/15 by pedestrian (grouped, Issue-5 protocol), per-fold
             pos_weight. No checkpoint dir -- the augmented result dict is written
             straight to out_path.
"""
import argparse
import importlib.util
import json
import pickle
from pathlib import Path

import numpy as np


def loso_fold_data(X, y, set_ids, ped_ids, fold_set, seed, val_frac=0.15):
    te = set_ids == fold_set
    pool = ~te
    pool_peds = np.unique(ped_ids[pool])
    rng = np.random.default_rng(seed)
    rng.shuffle(pool_peds)
    n_val = max(1, int(round(len(pool_peds) * val_frac)))
    val_peds = set(pool_peds[:n_val].tolist())
    is_val = np.array([p in val_peds for p in ped_ids])
    va = pool & is_val
    tr = pool & ~is_val
    data = (X[tr], y[tr], X[va], y[va], X[te], y[te])
    pw = float((y[tr] == 0).sum() / max(1, (y[tr] == 1).sum()))
    counts = dict(train_n=int(tr.sum()), val_n=int(va.sum()), test_n=int(te.sum()),
                 test_pos=float(y[te].mean()))
    return data, pw, counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jobs", required=True)
    ap.add_argument("--seq_dir", required=True)
    ap.add_argument("--here", required=True)
    args = ap.parse_args()

    here = Path(args.here)
    spec = importlib.util.spec_from_file_location("train_engine", here / "02_train_transformer.py")
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)

    import torch
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    seq_dir = Path(args.seq_dir)
    X, y, set_ids = engine.load_raw(seq_dir)
    fixed_data = engine.split_data(X, y, set_ids)
    with open(seq_dir / "meta.pkl", "rb") as f:
        meta = pickle.load(f)
    ped_ids = np.array([f"{m['set_id']}/{m['ped_id']}" for m in meta])

    jobs = json.loads(Path(args.jobs).read_text())

    for job in jobs:
        if job["kind"] == "final":
            out_dir = Path(job["out_dir"])
            if (out_dir / "final.json").exists():
                print(f"[worker] cached final {job.get('tag', '?')} seed{job['seed']} "
                      f"-> {out_dir}", flush=True)
                continue
            result = engine.train_run(job["cfg"], job["seed"], device, fixed_data,
                                      eval_test=True, out_dir=out_dir)
            print(f"[worker] done final {job.get('tag', '?')} seed{job['seed']} "
                  f"valAUC={result['val']['auc']:.4f} testAUC={result['test']['auc']:.4f} "
                  f"({result['seconds']}s)", flush=True)

        elif job["kind"] == "loso":
            out_path = Path(job["out_path"])
            if out_path.exists():
                print(f"[worker] cached loso {job['fold_set']}", flush=True)
                continue
            data, pw, counts = loso_fold_data(X, y, set_ids, ped_ids, job["fold_set"],
                                              job["seed"])
            result = engine.train_run(job["cfg"], job["seed"], device, data,
                                      eval_test=True, out_dir=None, pos_weight=pw)
            result.update(test_set=job["fold_set"], **counts)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(result, indent=2, default=str))
            print(f"[worker] done loso {job['fold_set']} valAUC={result['val']['auc']:.4f} "
                  f"testAUC={result['test']['auc']:.4f} pw={pw:.3f} "
                  f"({result['seconds']}s)", flush=True)

        else:
            raise ValueError(f"unknown job kind: {job['kind']!r}")


if __name__ == "__main__":
    main()
'''

# --- notebook cell sources (as plain python source strings) ---

CELL_MD_TITLE = """# Transformer final training (Stage D) + determinism rerun + 6-fold LOSO CV

Runs `transformer/PLAN.md` Phase T4: trains the Phase-T3 winner (`transformer_searched`)
and the pre-registered `transformer_default`, 5 seeds each, with **test set03 evaluated
here and nowhere else in the entire project**. Also runs a seed-42
determinism-of-record rerun (must reproduce its own numbers -- the Issue-2 "seed 42
reproduces 0.9131" precedent applied to the transformer) and the 6-fold
leave-one-set-out CV (Issue-5 protocol) on the winner config.

**Winner config** (from `phase3_search_review/03_search_summary.md`, Phase T3, reviewed
and confirmed by the user before this notebook was built):
`d128_ff512_L4_last_spe__adam_lr1e-03_plateau_do0.1_wd1e-05` -- d_model=128,
num_layers=4, dim_ff=512, pool="last", pos="sin", Adam lr=1e-3/plateau/dropout=0.1/wd=1e-5.
Val AUC (5-seed) 0.9789 +/- 0.0038, beating `transformer_default`'s 0.9629 +/- 0.0056
(which ranked 66th/78 in the seed-42 architecture pool). The literal config dict below
was copied from that config's raw `seed42.json` in `phase2_kaggle_search/runs_search/`,
not hand-parsed from the cfg_id string.

**Setup before Run All:**
1. Upload `sequences_clean/{X.npy,y.npy,meta.pkl}` (`transformer/sequences_clean/` in the
   repo) as a private Kaggle dataset named `pie-sequences-clean`, and attach it to this
   notebook (same dataset Phase T2 used).
2. Settings -> Accelerator -> **GPU T4 x2**.
3. Run All.

**Output:** 10 full run dirs (`runs_final/transformer_{searched,default}/seed<k>/
{best.pt, final.json, history.json, norm_mean.npy, norm_std.npy}`) + 1 determinism-rerun
dir + 6 LOSO fold JSONs (`runs_loso/<fold>.json`), zipped to
`/kaggle/working/transformer_final_output.zip`. Download it and unzip its contents
directly into `transformer/phase4_kaggle_final/`.

Nothing here should diverge from `transformer/PLAN.md` sections 4 and 7 (Phase T4) --
if it does, PLAN.md is stale and should be corrected, not this notebook."""

CELL_ENV_CHECK = """import json, sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

print("python:", sys.version)
print("torch:", torch.__version__)
n_gpu = torch.cuda.device_count()
print("CUDA available:", torch.cuda.is_available(), "| device count:", n_gpu)
for i in range(n_gpu):
    print(f"  cuda:{i} = {torch.cuda.get_device_name(i)}")
if n_gpu != 2:
    print(f"WARNING: expected 2x T4 (transformer/PLAN.md #5), found {n_gpu} GPU(s). "
          f"Continuing with {max(n_gpu, 1)} worker(s) -- this only affects wall-clock, "
          f"not correctness.")

GPU_IDS = list(range(n_gpu)) if n_gpu > 0 else [None]  # None => CPU fallback (slow, not expected)
print("worker GPU ids:", GPU_IDS)"""

CELL_LOCATE_DATA = """candidates = [Path("/kaggle/input/pie-sequences-clean")]
candidates += sorted(Path("/kaggle/input").glob("*"))
SEQ_DIR = None
for c in candidates:
    if (c / "X.npy").exists() and (c / "y.npy").exists() and (c / "meta.pkl").exists():
        SEQ_DIR = c
        break
assert SEQ_DIR is not None, (
    "Could not find sequences_clean/{X.npy,y.npy,meta.pkl} under /kaggle/input/. "
    "Attach the 'pie-sequences-clean' dataset (see the markdown cell above)."
)
print("using sequences from:", SEQ_DIR)

X_check = np.load(SEQ_DIR / "X.npy", mmap_mode="r")
assert X_check.shape == (4906, 16, 5), (
    f"unexpected X shape {X_check.shape} -- this must be the CLEAN sequences_clean/ "
    f"(N=4906), not the old leaky sequences/ (N=1389). Re-upload the correct dataset."
)
print(f"asserted clean data: X.shape == {X_check.shape}")

import pickle
with open(SEQ_DIR / "meta.pkl", "rb") as f:
    _meta_check = pickle.load(f)
assert len(_meta_check) == 4906, f"unexpected meta.pkl length {len(_meta_check)}"
print(f"asserted meta.pkl present with {len(_meta_check)} rows (needed for LOSO's "
     f"pedestrian-grouped fold splitting)")

HERE_DIR = Path("/kaggle/working")
print("HERE_DIR:", HERE_DIR)"""

CELL_WRITE_MODEL = f"""# KEEP IN SYNC WITH transformer/phase1_setup/00_transformer_model.py -- edit there
# first, then regenerate this notebook (see gen_final_nb.py). Do not hand-edit this cell.
model_code = {MODEL_CODE!r}
(HERE_DIR / "00_transformer_model.py").write_text(model_code)
print("wrote", HERE_DIR / "00_transformer_model.py", f"({{len(model_code)}} bytes)")"""

CELL_WRITE_ENGINE = """# KEEP IN SYNC WITH transformer/phase1_setup/02_train_transformer.py -- edit there
# first, then regenerate this notebook (see gen_final_nb.py). Do not hand-edit this cell.
engine_code = %r
(HERE_DIR / "02_train_transformer.py").write_text(engine_code)
print("wrote", HERE_DIR / "02_train_transformer.py", f"({len(engine_code)} bytes)")

import importlib.util
_spec_engine = importlib.util.spec_from_file_location(
    "train_engine", HERE_DIR / "02_train_transformer.py")
engine = importlib.util.module_from_spec(_spec_engine)
_spec_engine.loader.exec_module(engine)
print("loaded engine module; DEFAULT_CFG =", engine.DEFAULT_CFG)""" % ENGINE_CODE

CELL_WRITE_WORKER = f"""# Auto-generated worker script -- see gen_final_nb.py's WORKER_CODE.
worker_code = {WORKER_CODE!r}
(HERE_DIR / "worker_final.py").write_text(worker_code)
print("wrote", HERE_DIR / "worker_final.py", f"({{len(worker_code)}} bytes)")"""

CELL_HELPERS = """# --- output layout + the 2-GPU subprocess runner (same subprocess-per-GPU pattern as
# phase2_kaggle_search/03_search_kaggle.ipynb; jobs here carry their own absolute
# out_dir/out_path, so unlike the search worker, this one needs no --out_root arg). ---
import os, subprocess, sys, tempfile, time

OUT_ROOT = HERE_DIR / "phase4_out"
(OUT_ROOT / "runs_final").mkdir(parents=True, exist_ok=True)
(OUT_ROOT / "runs_loso").mkdir(parents=True, exist_ok=True)
print("OUT_ROOT:", OUT_ROOT)


def run_stage_parallel(jobs, gpu_ids, label=""):
    shards = [[] for _ in gpu_ids]
    for i, job in enumerate(jobs):
        shards[i % len(gpu_ids)].append(job)

    procs, shard_files = [], []
    t0 = time.time()
    for gpu, shard in zip(gpu_ids, shards):
        if not shard:
            continue
        f = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, dir=str(HERE_DIR))
        json.dump(shard, f)
        f.close()
        shard_files.append(f.name)
        env = dict(os.environ)
        if gpu is not None:
            env["CUDA_VISIBLE_DEVICES"] = str(gpu)
        proc = subprocess.Popen(
            [sys.executable, str(HERE_DIR / "worker_final.py"),
             "--jobs", f.name, "--seq_dir", str(SEQ_DIR), "--here", str(HERE_DIR)],
            env=env,
        )
        procs.append(proc)
        print(f"[{label}] launched worker on gpu={gpu} with {len(shard)} job(s)")

    for p in procs:
        ret = p.wait()
        if ret != 0:
            raise RuntimeError(f"[{label}] worker exited with code {ret}")
    for fn in shard_files:
        os.unlink(fn)
    print(f"[{label}] all workers done in {time.time() - t0:.0f}s")"""

CELL_CONFIG = """# Stage-C winner, verified 2026-07-11 directly from its raw seed42.json (not
# hand-parsed from the cfg_id string) -- see phase3_search_review/03_search_summary.md.
# val AUC (5-seed) 0.9789 +/- 0.0038 vs transformer_default's 0.9629 +/- 0.0056.
WINNER_CFG = dict(
    d_model=128, nhead=4, num_layers=4, dim_ff=512, dropout=0.1,
    pool="last", pos="sin",
    lr=1e-3, schedule="plateau", weight_decay=1e-5, optimizer="adam",
)
DEFAULT_CFG = engine.DEFAULT_CFG  # transformer_default -- imported, not hand-copied
CONFIGS = {"transformer_searched": WINNER_CFG, "transformer_default": DEFAULT_CFG}
SEEDS = [42, 0, 1, 2, 3]

print("transformer_searched (winner):", WINNER_CFG)
print("transformer_default          :", DEFAULT_CFG)
assert WINNER_CFG != DEFAULT_CFG, (
    "winner should differ from default -- otherwise the search picked nothing new")"""

CELL_STAGE_D = """print("=== Stage D: transformer_searched + transformer_default, 5 seeds each, eval_test=True ===")
print("*** THIS IS THE ONLY PLACE test set03 IS EVALUATED IN THE ENTIRE PROJECT. ***")

stage_d_jobs = []
for tag, cfg in CONFIGS.items():
    for seed in SEEDS:
        out_dir = OUT_ROOT / "runs_final" / tag / f"seed{seed}"
        stage_d_jobs.append(dict(kind="final", cfg=cfg, seed=seed, tag=tag, out_dir=str(out_dir)))
assert len(stage_d_jobs) == 10, len(stage_d_jobs)

run_stage_parallel(stage_d_jobs, GPU_IDS, label="Stage D")


def load_final(job):
    final = json.loads((Path(job["out_dir"]) / "final.json").read_text())
    return {**job, **final}


stage_d_results = [load_final(j) for j in stage_d_jobs]
df_d = pd.DataFrame([
    {"tag": r["tag"], "seed": r["seed"], "val_auc": r["val"]["auc"], "test_auc": r["test"]["auc"]}
    for r in stage_d_results
])
print(df_d.to_string(index=False))

stage_d_summary = []
for tag in CONFIGS:
    sub = df_d[df_d.tag == tag]
    stage_d_summary.append(dict(
        tag=tag, n=len(sub),
        val_auc_mean=float(sub.val_auc.mean()), val_auc_std=float(sub.val_auc.std(ddof=1)),
        test_auc_mean=float(sub.test_auc.mean()), test_auc_std=float(sub.test_auc.std(ddof=1)),
    ))
df_d_summary = pd.DataFrame(stage_d_summary)
print("\\n5-seed summary:")
print(df_d_summary.to_string(index=False))"""

CELL_DETERMINISM = """print("\\n=== Determinism-of-record rerun: transformer_searched seed42, independent re-run ===")
primary_job = next(j for j in stage_d_jobs if j["tag"] == "transformer_searched" and j["seed"] == 42)
primary_final = json.loads((Path(primary_job["out_dir"]) / "final.json").read_text())

rerun_out_dir = OUT_ROOT / "runs_final" / "_determinism_check" / "transformer_searched_seed42_rerun"
rerun_job = dict(kind="final", cfg=WINNER_CFG, seed=42, tag="transformer_searched_rerun",
                 out_dir=str(rerun_out_dir))
run_stage_parallel([rerun_job], GPU_IDS, label="Determinism rerun")
rerun_final = json.loads((rerun_out_dir / "final.json").read_text())

val_delta = abs(rerun_final["val"]["auc"] - primary_final["val"]["auc"])
test_delta = abs(rerun_final["test"]["auc"] - primary_final["test"]["auc"])
print(f"primary  val_auc={primary_final['val']['auc']:.6f}  test_auc={primary_final['test']['auc']:.6f}")
print(f"rerun    val_auc={rerun_final['val']['auc']:.6f}  test_auc={rerun_final['test']['auc']:.6f}")
print(f"|delta|  val={val_delta:.2e}  test={test_delta:.2e}")

determinism_ok = val_delta < 1e-6 and test_delta < 1e-6
print("DETERMINISM CHECK:", "PASS" if determinism_ok
     else "WARN -- did not reproduce exactly; investigate before trusting the headline number")"""

CELL_LOSO = """print("\\n=== LOSO: 6-fold leave-one-set-out CV, transformer_searched, seed 42 (Issue-5 protocol) ===")
SIX_SETS = ["set01", "set02", "set03", "set04", "set05", "set06"]

loso_jobs = []
for s in SIX_SETS:
    out_path = OUT_ROOT / "runs_loso" / f"{s}.json"
    loso_jobs.append(dict(kind="loso", cfg=WINNER_CFG, seed=42, fold_set=s, out_path=str(out_path)))
assert len(loso_jobs) == 6, len(loso_jobs)

run_stage_parallel(loso_jobs, GPU_IDS, label="LOSO")

loso_results = [json.loads(Path(j["out_path"]).read_text()) for j in loso_jobs]
loso_rows = [{
    "fold": r["test_set"], "test_n": r["test_n"], "test_pos_pct": r["test_pos"] * 100,
    "auc": r["test"]["auc"], "pr_auc": r["test"]["pr_auc"], "f1": r["test"]["f1"],
    "acc": r["test"]["acc"], "pos_weight": r["pos_weight"], "best_epoch": r["best_epoch"],
} for r in loso_results]
df_loso = pd.DataFrame(loso_rows)
print(df_loso.to_string(index=False))

aucs = df_loso["auc"].to_numpy()
print(f"\\nMean +/- std over 6 folds (unweighted): AUC {aucs.mean():.4f} +/- {aucs.std(ddof=1):.4f}")
big = df_loso[df_loso.test_n >= 100]
if 0 < len(big) < len(df_loso):
    big_aucs = big["auc"].to_numpy()
    print(f"Excluding small folds (N<100): AUC {big_aucs.mean():.4f} +/- {big_aucs.std(ddof=1):.4f} "
         f"(n={len(big)} folds)")"""

CELL_SAVE_ZIP = """# n_params isn't in final.json (that schema is deliberately minimal, matching
# pipeline/05_compare_runs.py's expectations -- see phase1_setup/02_train_transformer.py)
# so it's recomputed from cfg here -- params are a pure function of architecture, not
# of the training run.
final_summary = {
    "stage_d": [{"tag": r["tag"], "seed": r["seed"], "val": r["val"], "test": r["test"],
                "n_params": engine.count_params(engine.build_model(r["cfg"])),
                "best_epoch": r["best_epoch"]}
               for r in stage_d_results],
    "stage_d_summary": stage_d_summary,
    "determinism_check": {
        "primary": {"val_auc": primary_final["val"]["auc"], "test_auc": primary_final["test"]["auc"]},
        "rerun": {"val_auc": rerun_final["val"]["auc"], "test_auc": rerun_final["test"]["auc"]},
        "val_delta": val_delta, "test_delta": test_delta, "pass": determinism_ok,
    },
    "loso": loso_rows,
    "winner_cfg": WINNER_CFG,
    "default_cfg": DEFAULT_CFG,
    "seeds": SEEDS,
}
(OUT_ROOT / "_final_summary.json").write_text(json.dumps(final_summary, indent=2, default=str))
print("wrote", OUT_ROOT / "_final_summary.json")

import shutil
zip_path = Path("/kaggle/working/transformer_final_output.zip")
if zip_path.exists():
    zip_path.unlink()
shutil.make_archive(str(zip_path.with_suffix("")), "zip", root_dir=str(OUT_ROOT))
print(f"\\nDONE. Download {zip_path} and unzip its CONTENTS directly into "
     f"transformer/phase4_kaggle_final/ (e.g. unzip transformer_final_output.zip -d "
     f"transformer/phase4_kaggle_final/) so runs_final/, runs_loso/, and "
     f"_final_summary.json sit there directly, then run the phase5_analysis/ scripts "
     f"locally (not yet built as of this notebook's generation).")"""

CELL_MD_NEXT = """## Next steps

1. Download `/kaggle/working/transformer_final_output.zip`.
2. Unzip its contents directly into `transformer/phase4_kaggle_final/`, e.g.:
   `unzip transformer_final_output.zip -d transformer/phase4_kaggle_final/`
   so `runs_final/`, `runs_loso/`, and `_final_summary.json` sit there.
3. Confirm the printed **DETERMINISM CHECK: PASS** above before trusting the headline
   test numbers -- if it says WARN, investigate before proceeding.
4. Phase T5 (`transformer/phase5_analysis/`, not yet built as of this notebook's
   generation): aggregate `runs_final/` into 5-seed tables, run the paired-bootstrap
   comparison against the frozen LSTM checkpoints, benchmark latency, and report the
   LOSO fold table -- see `transformer/PLAN.md` section 7 (Phase T5) for the exact
   scripts and acceptance criteria."""


def code_cell(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}


cells = [
    md_cell(CELL_MD_TITLE),
    code_cell(CELL_ENV_CHECK),
    code_cell(CELL_LOCATE_DATA),
    code_cell(CELL_WRITE_MODEL),
    code_cell(CELL_WRITE_ENGINE),
    code_cell(CELL_WRITE_WORKER),
    code_cell(CELL_HELPERS),
    code_cell(CELL_CONFIG),
    code_cell(CELL_STAGE_D),
    code_cell(CELL_DETERMINISM),
    code_cell(CELL_LOSO),
    code_cell(CELL_SAVE_ZIP),
    md_cell(CELL_MD_NEXT),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out_path = HERE / "04_final_loso_kaggle.ipynb"
out_path.write_text(json.dumps(notebook, indent=1))
print("wrote", out_path)

# --- validate: JSON parses, every code cell compiles ---
loaded = json.loads(out_path.read_text())
n_code = 0
for i, cell in enumerate(loaded["cells"]):
    if cell["cell_type"] != "code":
        continue
    n_code += 1
    src = cell["source"]
    compile(src, f"<cell {i}>", "exec")
print(f"OK -- {n_code} code cells compiled without SyntaxError")
