"""worker.py -- one GPU-pinned training worker for the Kaggle search notebook.
Auto-generated by kaggle/03_search_kaggle.ipynb -- edit the notebook cell, not this file.
CUDA_VISIBLE_DEVICES is set by the parent process before this script starts, so
torch.device("cuda") always refers to this worker's assigned physical GPU.
"""
import argparse
import importlib.util
import json
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jobs", required=True)
    ap.add_argument("--seq_dir", required=True)
    ap.add_argument("--out_root", required=True)
    ap.add_argument("--here", required=True)
    args = ap.parse_args()

    here = Path(args.here)
    spec = importlib.util.spec_from_file_location("train_engine", here / "02_train_transformer.py")
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)

    import torch
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    X, y, set_ids = engine.load_raw(Path(args.seq_dir))
    data = engine.split_data(X, y, set_ids)

    jobs = json.loads(Path(args.jobs).read_text())
    out_root = Path(args.out_root)

    for job in jobs:
        assert not job["eval_test"], (
            "search notebook must never evaluate the test set -- "
            f"got eval_test=True for {job['cfg_id']} seed{job['seed']}"
        )
        out_path = out_root / job["cfg_id"] / f"seed{job['seed']}.json"
        if out_path.exists():
            print(f"[worker] cached {job['cfg_id']} seed{job['seed']}", flush=True)
            continue
        out_path.parent.mkdir(parents=True, exist_ok=True)
        result = engine.train_run(job["cfg"], job["seed"], device, data,
                                  eval_test=False, out_dir=None)
        out_path.write_text(json.dumps(result, indent=2, default=str))
        print(f"[worker] done {job['cfg_id']} seed{job['seed']} "
              f"valAUC={result['val']['auc']:.4f} ({result['seconds']}s)", flush=True)


if __name__ == "__main__":
    main()
